apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: ecommerce-pod
  ports:
    - port: 80
      protocol: TCP
      targetPort: 7001
      nodePort: 32767